// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// stl_sort
NumericVector stl_sort(NumericVector x);
RcppExport SEXP LAS_stl_sort(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(stl_sort(x));
    return __result;
END_RCPP
}
// normalizeInput
void normalizeInput(NumericVector& x);
RcppExport SEXP LAS_normalizeInput(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector& >::type x(xSEXP);
    normalizeInput(x);
    return R_NilValue;
END_RCPP
}
// normalizeInputMatrix
NumericMatrix normalizeInputMatrix(NumericMatrix& x);
RcppExport SEXP LAS_normalizeInputMatrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    __result = Rcpp::wrap(normalizeInputMatrix(x));
    return __result;
END_RCPP
}
